version: '3'
services:
  web1:
    build:
      context: ./web1/
  web2:
    build:
      context: ./web2/
  web3:
    build:
      context: ./web3/
  nginx:
    image: "nginx:1.15.6-alpine"
    ports:
     - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - web1
      - web2
      - web3
